export type HeaderXmlObject = {
    GeneratedByEngineVersion: string,
    RequiredEngineVersion: string,
    Encrypted: string,
    Encoding: string,
    Format: string,
    CreationDate: string,
    Compact: string,
    Compat: string,
    KeyCaseSensitive: string,
    Description: string,
    Title: string,
    DataSourceFormat: string,
    StyleSheet: string,
    RegisterBy: string,
    RegCode: string,
    StripKey: string,
}